<a href="https://colab.research.google.com/github/bharaniakella/Akellianpuff/blob/main/merge_two_Sorted_Arrays_Extra_space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
arr1=np.array([1,4,8,10])
arr2=np.array([2,3,9])

In [58]:
def merge_sorted_array(arr1,arr2):
  a1_len=len(arr1)
  a2_len=len(arr2)
  arr3=np.zeros(a1_len+a2_len)
  a3_len=len(arr3)
  while(a1_len>0 and a2_len>0):
    if(arr1[a1_len-1]>arr2[a2_len-1]):
      arr3[a3_len-1]=arr1[a1_len-1]
      print(arr3)
      a1_len=a1_len-1
    else:
      arr3[a3_len-1]=arr2[a2_len-1]
      print(arr3)
      a2_len=a2_len-1
    a3_len=a3_len-1
  while(a1_len>0):
    arr3[a3_len-1]=arr1[a1_len-1]
    a1_len=a1_len-1
    a3_len=a3_len-1
  while(a2_len>0):
    arr3[a3_len-1]=arr1[a2_len-1]
    a2_len=a2_len-1
    a3_len=a3_len-1
  return arr3




In [59]:
merge_sorted_array(arr1,arr2)

[ 0.  0.  0.  0.  0.  0. 10.]
[ 0.  0.  0.  0.  0.  9. 10.]
[ 0.  0.  0.  0.  8.  9. 10.]
[ 0.  0.  0.  4.  8.  9. 10.]
[ 0.  0.  3.  4.  8.  9. 10.]
[ 0.  2.  3.  4.  8.  9. 10.]


array([ 1.,  2.,  3.,  4.,  8.,  9., 10.])